### ISSUE TITLE
#29: CFNotifyPop doesn't works.

### ISSUE THREAD

**Issue by ghost** [karashiiro/FFXIVOpcodeWizard#10]
I use Chineses client and other function works well. But when I try to use #29, the program doesn't give any response. What should I do?

**Comment by karashiiro** [comment]
In the debug console of the program, it outputs all of the opcodes it comes across, you could try watching that for unique opcodes when you pull up the duty pop for the dungeon and testing them. The packet flags that scanner uses might not be specific enough, or the packet might be slightly different for CN for some reason.
