### ISSUE TITLE
Can you add anything about duty?

### ISSUE THREAD

**Issue by ffxivvillein** [karashiiro/FFXIVOpcodeWizard#8]
Sorry, my english is bad.
I want roulette or queue opcode. 
Is there an easy way to find out?

**Comment by karashiiro** [comment]
I believe that's CFNotifyPop?
https://github.com/karashiiro/FFXIVOpcodeWizard/blob/master/FFXIVOpcodeWizard/WizardProcessor.cs#L166

**Comment by ffxivvillein** [comment]
https://github.com/qitana/ACT_DFAPlugin/blob/master/docs/data/structures.json
https://github.com/easly1989/ffxiv_act_dfassist/blob/master/DFAssist.Core/Network/FFXIVPacketHandler.cs#L44-L135
Many opcodes are used. I don't know how to get these opcodes.
If it's not possible automatically, can you tell me about any guide or tools involved?

**Comment by karashiiro** [comment]
I think CFNotifyPop is Matched? You really just need to open up ffxivmon and see what fires when the corresponding events happen. You can join the Sapphire Discord here: https://discord.gg/xxcdCER to search and ask in #ffxiv-community-dev about how to get set up with that.

**Comment by ffxivvillein** [comment]
Thank you for your kindness.
