### ISSUE TITLE
Does this program support CN server?

### ISSUE THREAD

**Issue by ghost** [karashiiro/FFXIVOpcodeWizard#9]
Does this program support CN server? If support, when program ask me "Please enter the current game version: ", what should I input? something like 5.05 or other thing?

**Comment by karashiiro** [comment]
Uh, it does as of two seconds ago >.>

For the game version, it is 5.05 currently.

**Comment by ghost** [comment]
Thx a lot. This program works well now.BTW, [FFXIVNetworkMonitor.cs#L90](https://github.com/karashiiro/FFXIVOpcodeWizard/blob/master/FFXIVOpcodeWizard/FFXIVNetworkMonitor.cs#L90) it should be ` _monitor.WindowName = Region == Region.CN ? "最终幻想XIV" : "FINAL FANTASY XIV";` not Common.Region.CN.

**Comment by karashiiro** [comment]
Ah, whoops, forgot to change that, thank you ^^
